/**
 *	Copyright (c) 2013 James Walmsley
 *
 *
 **/

#include <bitthunder.h>
#include "bt_types.h"

#include <FreeRTOS.h>
#include <task.h>
#include <portmacro.h>

struct _BT_OPAQUE_HANDLE {
	BT_HANDLE_HEADER h;
};

/* Constants required to handle critical sections. */
#define portNO_CRITICAL_NESTING		( ( unsigned long ) 0 )
volatile unsigned long ulCriticalNesting = 9999UL;

static BT_ERROR tick_isr_handler(BT_u32 ulIRQ, void *pParam) {
	vTaskIncrementTick();

#if configUSE_PREEMPTION == 1
	vTaskSwitchContext();
#endif

	// Timer interrupt status is handled automatically by BitThunder driver.
	return BT_ERR_NONE;
}

/* Constants required to setup the task context. */
/* System mode, ARM mode, interrupts enabled. */
#define portINITIAL_SPSR				( ( portSTACK_TYPE ) 0x1f )
#define portTHUMB_MODE_BIT				( ( portSTACK_TYPE ) 0x20 )
#define portINSTRUCTION_SIZE			( ( portSTACK_TYPE ) 4 )
#define portNO_CRITICAL_SECTION_NESTING	( ( portSTACK_TYPE ) 0 )

/**
 *	Initialise the stack of a task to look as if a call to
 *	portSAVE_CONTEXT has been called.
 *
 **/
/*
 * See header file for description.
 */
portSTACK_TYPE *pxPortInitialiseStack( portSTACK_TYPE *pxTopOfStack, pdTASK_CODE pxCode, void *pvParameters )
{
	/* Simulate the stack frame as it would be created by a context switch
	interrupt. */
	*pxTopOfStack = portINITIAL_XPSR;	             /* xPSR */
	pxTopOfStack--;
	*pxTopOfStack = ( portSTACK_TYPE ) pxCode;	     /* Return address (new PC) */
	pxTopOfStack--;
	*pxTopOfStack = 0;	                             /* LR (R14) */
	pxTopOfStack -= 5;	                             /* R12, R3, R2, R1 */
	*pxTopOfStack = ( portSTACK_TYPE ) pvParameters; /* and R0 */
	pxTopOfStack -= 8;	/* R7, R6, R5, R4, R11, R10, R9, and R8. */
	return pxTopOfStack;
}


void vPortExitTask( void ) {
	vTaskDelete(NULL);
}


static void prvSetupTimerInterrupt(void) {

	BT_ERROR Error;
	BT_MACHINE_DESCRIPTION *pMachine = BT_GetMachineDescription(&Error);
	if(!pMachine) {
		return;
	}

	const BT_INTEGRATED_DRIVER *pDriver;
	BT_HANDLE hTimer = NULL;

	pDriver = BT_GetIntegratedDriverByName(pMachine->pSystemTimer->name);
	if(!pDriver) {
		return;
	}

	hTimer = pDriver->pfnProbe(pMachine->pSystemTimer, &Error);
	if(!hTimer) {
		return;
	}

	BT_SetSystemTimerHandle(hTimer);

	const BT_DEV_IF_SYSTIMER *pTimerOps = hTimer->h.pIf->oIfs.pDevIF->unConfigIfs.pSysTimerIF;
	pTimerOps->pfnSetFrequency(hTimer, configTICK_RATE_HZ);
	pTimerOps->pfnRegisterInterrupt(hTimer, tick_isr_handler, NULL);
	pTimerOps->pfnEnableInterrupt(hTimer);
	pTimerOps->pfnStart(hTimer);
}


extern void enable_irq(void);

void vPortStartFirstTask( void )
{
	asm volatile(
					" ldr r0, =0x0	\n" /* cm0 has fixed vector table at address 0x0 */
					" ldr r0, [r0]	\n"
					" msr msp, r0	\n" /* Set the msp back to the start of the stack. */
					" svc 0			\n" /* System call to start first task. */
				);
}

portBASE_TYPE xPortStartScheduler(void) {
	// Setup Hardware Timer!
	prvSetupTimerInterrupt();
	// Start first task

	//uxCriticalNesting = 0;

	vPortISRStartFirstTask();

	// Should not get here!
	return 0;
}

/*
 *	Critical Sections.
 *
 **/

/* The code generated by the GCC compiler uses the stack in different ways at
different optimisation levels.  The interrupt flags can therefore not always
be saved to the stack.  Instead the critical section nesting level is stored
in a variable, which is then saved as part of the stack context. */
void vPortEnterCritical( void )
{
	/* Disable interrupts as per portDISABLE_INTERRUPTS(); 					*/
	portDISABLE_INTERRUPTS();
	uxCriticalNesting++;
}

void vPortExitCritical( void )
{
	uxCriticalNesting--;
	if(!uxCriticalNesting) {
		portENABLE_INTERRUPTS();
	}
}


void vPortEndScheduler( void )
{
	/* It is unlikely that the ARM port will require this function as there
	is nothing to return to.  */
}


void vPortYieldProcessor( void ) __attribute__((interrupt("SWI"), naked));

void vPortYieldProcessor( void )
{

	/* Within an IRQ ISR the link register has an offset from the true return
	address, but an SWI ISR does not.  Add the offset manually so the same
	ISR return code can be used in both cases. */
	__asm volatile ( "ADD		LR, LR, #4" );

	/* Perform the context switch. First save the context of the current
	task.*/
	portSAVE_CONTEXT();

	/* Find the highest priority task that is ready to run. */
	vTaskSwitchContext();

	__asm volatile( "clrex" );

	/* Restore the context of the new task. */
	portRESTORE_CONTEXT();
}

/*
 * FreeRTOS bottom-level IRQ vector handler
 */
void vFreeRTOS_IRQInterrupt ( void ) __attribute__((naked));
void vFreeRTOS_IRQInterrupt ( void )
{

	unsigned portLONG ulDummy;

	/* If using preemption, also force a context switch. */
	#if configUSE_PREEMPTION == 1
		SCB->ICSR = portNVIC_PENDSVSET;
	#endif

	ulDummy = portSET_INTERRUPT_MASK_FROM_ISR();
	{
		vTaskIncrementTick();
	}
	portCLEAR_INTERRUPT_MASK_FROM_ISR( ulDummy );

	/* Save the context of the interrupted task. */
	portSAVE_CONTEXT();

	ulCriticalNesting++;

	__asm volatile( "clrex" );

	/* Call the handler provided with the standalone BSP */
	__asm volatile( "bl  BT_ARCH_ARM_GIC_IRQHandler" );

	ulCriticalNesting--;

	/* Restore the context of the new task. */
	portRESTORE_CONTEXT();
}
