#SUB_OBJDIRS += $(BASE)arch/$(ARCH)/mach/$(SUBARCH)/

BT_ARCH_ARM_OBJECTS-$(BT_CONFIG_ARCH_ARM_USE_GIC) += $(BUILD_DIR)arch/arm/common/gic.o


BT_ARCH_ARM_OBJECTS += $(BT_ARCH_ARM_OBJECTS-y)

$(BUILD_DIR)arch/arm/common/gic.o: CFLAGS += -DBT_CONFIG_ARCH_ARM_GIC_TOTAL_IRQS=$(BT_CONFIG_ARCH_ARM_GIC_TOTAL_IRQS)

$(BT_ARCH_ARM_OBJECTS): MODULE_NAME="HAL"
OBJECTS += $(BT_ARCH_ARM_OBJECTS)
