
BT_KERNEL_FREERTOS_OBJECTS += $(BUILD_DIR)kernel/FreeRTOS/Source/croutine.o
BT_KERNEL_FREERTOS_OBJECTS += $(BUILD_DIR)kernel/FreeRTOS/Source/list.o
BT_KERNEL_FREERTOS_OBJECTS += $(BUILD_DIR)kernel/FreeRTOS/Source/queue.o
BT_KERNEL_FREERTOS_OBJECTS += $(BUILD_DIR)kernel/FreeRTOS/Source/tasks.o
BT_KERNEL_FREERTOS_OBJECTS += $(BUILD_DIR)kernel/FreeRTOS/Source/portable/GCC/Zynq/port.o
BT_KERNEL_FREERTOS_OBJECTS += $(BUILD_DIR)kernel/FreeRTOS/Source/portable/GCC/Zynq/portISR.o

$(BT_KERNEL_FREERTOS_OBJECTS):MODULE_NAME="FreeRTOS"
$(BT_KERNEL_FREERTOS_OBJECTS):CFLAGS+=-I $(BASE)kernel/FreeRTOS/Source/include/
$(BT_KERNEL_FREERTOS_OBJECTS):CFLAGS += -I $(BASE)kernel/FreeRTOS/Source/portable/GCC/Zynq/

OBJECTS += $(BT_KERNEL_FREERTOS_OBJECTS)
