#
#	lm3sxx Platform objects
#
MACH_LM3Sxx_OBJECTS  += $(BUILD_DIR)/arch/arm/mach/lm3sxx/lm3sxx.o			# Provides machine description.
MACH_LM3Sxx_OBJECTS  += $(BUILD_DIR)/arch/arm/mach/lm3sxx/ioconfig.o
MACH_LM3Sxx_OBJECTS  += $(BUILD_DIR)/arch/arm/mach/lm3sxx/rcc.o
MACH_LM3Sxx_OBJECTS  += $(BUILD_DIR)/arch/arm/mach/lm3sxx/gpio.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_TIMER)    += $(BUILD_DIR)/arch/arm/mach/lm3sxx/timer.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_UART)     += $(BUILD_DIR)/arch/arm/mach/lm3sxx/uart.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_CAN)      += $(BUILD_DIR)/arch/arm/mach/lm3sxx/can.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_SPI)      += $(BUILD_DIR)/arch/arm/mach/lm3sxx/spi.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_I2C)      += $(BUILD_DIR)/arch/arm/mach/lm3sxx/i2c.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_ADC)      += $(BUILD_DIR)/arch/arm/mach/lm3sxx/adc.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_PWM)      += $(BUILD_DIR)/arch/arm/mach/lm3sxx/pwm.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_QEI)      += $(BUILD_DIR)/arch/arm/mach/lm3sxx/qei.o
MACH_LM3Sxx_OBJECTS-$(BT_CONFIG_MACH_LM3Sxx_MAC)	  += $(BUILD_DIR)/arch/arm/mach/lm3sxx/mac.o

MACH_LM3Sxx_OBJECTS += $(MACH_LM3Sxx_OBJECTS-y)

$(MACH_LM3Sxx_OBJECTS): MODULE_NAME="HAL"
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -D BT_CONFIG_MACH_LM3Sxx_SYSCLOCK_FREQ=$(BT_CONFIG_MACH_LM3Sxx_SYSCLOCK_FREQ)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -D BT_CONFIG_MACH_LM3Sxx_SYSCLOCK_IRC_FREQ=$(BT_CONFIG_MACH_LM3Sxx_SYSCLOCK_IRC_FREQ)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_ARCH_ARM_NVIC_BASE=$(BT_CONFIG_ARCH_ARM_NVIC_BASE)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_ARCH_ARM_NVIC_TOTAL_IRQS=$(BT_CONFIG_ARCH_ARM_NVIC_TOTAL_IRQS)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_MACH_LM3Sxx_TOTAL_GPIOS=$(BT_CONFIG_MACH_LM3Sxx_TOTAL_GPIOS)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_MACH_LM3Sxx_GPIO_BASE=$(BT_CONFIG_MACH_LM3Sxx_GPIO_BASE)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_MACH_LM3Sxx_CAN0_BASE=$(BT_CONFIG_MACH_LM3Sxx_CAN0_BASE)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_MACH_LM3Sxx_UART0_BASE=$(BT_CONFIG_MACH_LM3Sxx_UART0_BASE)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_MACH_LM3Sxx_TIMER0_BASE=$(BT_CONFIG_MACH_LM3Sxx_TIMER0_BASE)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_MACH_LM3Sxx_TIMER1_BASE=$(BT_CONFIG_MACH_LM3Sxx_TIMER1_BASE)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_MACH_LM3Sxx_TIMER2_BASE=$(BT_CONFIG_MACH_LM3Sxx_TIMER2_BASE)
$(MACH_LM3Sxx_OBJECTS): CFLAGS += -DBT_CONFIG_MACH_LM3Sxx_TIMER3_BASE=$(BT_CONFIG_MACH_LM3Sxx_TIMER3_BASE)



OBJECTS += $(MACH_LM3Sxx_OBJECTS)
