#
#	LPC11xx Platform objects
#
MACH_LPC11xx_OBJECTS += $(BUILD_DIR)arch/arm/mach/lpc11xx/lpc11xx.o			# Provides machine description.

MACH_LPC11xx_OBJECTS += $(BUILD_DIR)arch/arm/mach/lpc11xx/uart.o
MACH_LPC11xx_OBJECTS += $(BUILD_DIR)arch/arm/mach/lpc11xx/timer.o
MACH_LPC11xx_OBJECTS += $(BUILD_DIR)arch/arm/mach/lpc11xx/gpio.o

MACH_LPC11xx_OBJECTS += $(MACH_LPC11xx_OBJECTS-y)

$(MACH_LPC11xx_OBJECTS): MODULE_NAME="HAL"
#$(MACH_LPC11xx_OBJECTS): CFLAGS += -D BT_CONFIG_MACH_ZYNQ_SYSCLOCK_FREQ=$(BT_CONFIG_MACH_ZYNQ_SYSCLOCK_FREQ)
#$(MACH_LPC11xx_OBJECTS): CFLAGS += -D BT_CONFIG_MACH_ZYNQ_SYSTICK_TIMER_ID=$(BT_CONFIG_MACH_ZYNQ_SYSTICK_TIMER_ID)
#$(MACH_LPC11xx_OBJECTS): CFLAGS += -D BT_CONFIG_MACH_ZYNQ_BOOT_UART_ID=$(BT_CONFIG_MACH_ZYNQ_BOOT_UART_ID)

OBJECTS += $(MACH_LPC11xx_OBJECTS)
