#include <bt_config.h>


#ifdef BT_CONFIG_LINKER_INIT_SECTION_FLASH
#define BT_LINKER_INIT_SECTION	FLASH
#endif

#ifdef BT_CONFIG_LINKER_INIT_SECTION_SRAM
#define BT_LINKER_INIT_SECTION	SRAM
#endif

#ifdef BT_CONFIG_LINKER_INIT_SECTION_RAM
#define BT_LINKER_INIT_SECTION	RAM
#endif
