BLOCK_OBJECTS-$(BT_CONFIG_DRIVERS_BLOCK_RAMDISK) += $(BUILD_DIR)/drivers/block/ramdisk.o


BLOCK_OBJECTS += $(BLOCK_OBJECTS-y)

$(BLOCK_OBJECTS): MODULE_NAME="drivers-BLOCK"
OBJECTS += $(BLOCK_OBJECTS)
